# Generated by snakegit

import setuptools
import ConfigParser

parser = ConfigParser.RawConfigParser()
parser.read('snake.cfg')

setuptools.setup(name=parser.get('release', 'name'),
    version=parser.get('release', 'version'),
    package_dir={'': 'src'},
    packages=setuptools.find_packages('src'),
    provides=setuptools.find_packages('src')
    )
